[workspace]
members = [
    "programs/*",
    "fomo3d-raydium-cp-swap-client",
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
